### ISSUE TITLE
Проверить ДЗ 7

### ISSUE THREAD

**Issue by HelgaJava** [HelgaJava/git-homework7HousesDb#1]
Лямбды идут туго. Я вроде поняла принцип, что в правой части идут аргументы, далее выражения, в которых используются эти аргументы. С сортировкой вроде все получилось. С поиском трудности: не могу понять как использовать lambda в equals. По логике там 1 аргумент, который нужно передать. Equals возвращает boolean. Поэтому был такой вариант (в цикле по houses:
boolean search = o->houses.getDistrict().equals("Вахитовский") и далее если search = true, тогда добавляем house в новый список.
Далее все варианты крутились около него. Idea постоянно выдает ошибки. 
Пока сделала поиск через выборку в запросе, я понимаю, что это не то, что должно быть по заданию. В общем, подскажите, пожалуйста, в какую сторону копать в случае с lambda в equals. Ну или я вообще что-то не так понимаю.

**Comment by coursar** [comment]
С equals не нужно, это будет в Stream API, когда будете делать Filter. Пока оставляйте, как было.
