### ISSUE TITLE
Это всё-таки больше утилитные классы, нежели бизнес-логика (по поводу суфикса Service)

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework7HousesDb#3]
https://github.com/HelgaJava/git-homework7HousesDb/blob/99c9c67f081c80ed1b9227e0b20add18eabe2915/src/main/java/ru/itpark/service/JdbcTemplateService.java#L12

**Comment by HelgaJava** [comment]
убрала суффиксы
