### ISSUE TITLE
@Data за вас генерирует equals и hashCode, в чём особенность ваших?

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework7HousesDb#4]
https://github.com/HelgaJava/git-homework7HousesDb/blob/99c9c67f081c80ed1b9227e0b20add18eabe2915/src/main/java/ru/itpark/model/House.java#L16-L36

**Comment by HelgaJava** [comment]
исправила

**Comment by HelgaJava** [comment]
просто до этого на занятиях мы все время эти методы переопределяли. То, что раюотает и без этого, я еще по прошлой домашке заметила. Тогда зачем мы это делали? Я по предыдущей домашке хотела этот вопрос задать, забыла просто.

**Comment by coursar** [comment]
Мы учились и смотрели на это, а так:
1. Стандартным способом переопределяет Lombok
1. Нестандартным - мы будем использовать Stream API и лямбды

**Comment by coursar** [comment]
Есть ещё вариант, что если вы не используете Lombok, тогда вам постоянно придэтся об этом помнить.
